name: Minipost Aspire Deploy

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Install Aspire CLI
        run: |
          curl -sSL https://aspire.dev/install.sh | bash
          echo "$HOME/.aspire/bin" >> $GITHUB_PATH

      - name: Output Aspire CLI version
        run: aspire --version

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push iamges
        env:
          REGISTRY_ENDPOINT: docker.io
          REGISTRY_REPOSITORY: ${{ secrets.DOCKERHUB_USERNAME }}
        run: aspire do push

      - name: Prepare Docker Compose with Aspire
        run: |
          aspire publish \
          --project AppHost/AppHost.csproj \
          --output-path ./aspire-output

      - name: Upload Aspire artifacts
        uses: appleboy/scp-action@v1
        with:
          timeout: 120s
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          source: "aspire-output/docker-compose.yaml"
          target: "~/minipost"

      - name: Deploy via Docker Compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          script: |
            cd ~/minipost/aspire-output
            docker compose pull
            docker compose up -d --remove-orphans
  